%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-ros-core
Version:        1.5.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ros_core package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-noetic-catkin
Requires:       ros-noetic-class-loader
Requires:       ros-noetic-cmake-modules
Requires:       ros-noetic-common-msgs
Requires:       ros-noetic-gencpp
Requires:       ros-noetic-geneus
Requires:       ros-noetic-genlisp
Requires:       ros-noetic-genmsg
Requires:       ros-noetic-gennodejs
Requires:       ros-noetic-genpy
Requires:       ros-noetic-message-generation
Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-pluginlib
Requires:       ros-noetic-ros
Requires:       ros-noetic-ros-comm
Requires:       ros-noetic-rosbag-migration-rule
Requires:       ros-noetic-rosconsole
Requires:       ros-noetic-rosconsole-bridge
Requires:       ros-noetic-roscpp-core
Requires:       ros-noetic-rosgraph-msgs
Requires:       ros-noetic-roslisp
Requires:       ros-noetic-rospack
Requires:       ros-noetic-std-msgs
Requires:       ros-noetic-std-srvs
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A metapackage to aggregate the packages required to use publish / subscribe,
services, launch files, and other core ROS concepts.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue May 19 2020 Mikael Arguedas <mikael@osrfoundation.org> - 1.5.0-1
- Autogenerated by Bloom

